RHELMISC-8207: Enable NTP server and time sync
HCK-CI/HLK-Setup-Scripts pull request #23
Opened 2024-12-13 13:51 UTC by Jedoku

2024-12-16 10:31 UTC, kostyanf14 commented on client.ps1
> +    w32tm /config /manualpeerlist:$STUDIOIP /syncfromflags:manual /reliable:NO /largephaseoffset:0 /update
Does this command fail with the `Execute-Command` helper or why do not use it?

2024-12-16 10:31 UTC, kostyanf14 commented on studio.ps1
> +    New-NetFirewallRule -Name "NTP_Inbound" -DisplayName "Inbound NTP" -Protocol UDP -LocalPort 123 -Direction Inbound -Action Allow
Why do we need `New-NetFirewallRule`, we disable the firewall at the first stage?

2024-12-19 09:17 UTC, akihikodaki requested changes

2024-12-19 09:17 UTC, akihikodaki commented on client.ps1
> +    Execute-Command -Path "w32tm.exe" -Arguments "/resync /nowait"
Don't synchronize time here. The studio is not up yet and I don't think we need time synchronized during installation anyway.

2024-12-26 08:35 UTC, akihikodaki requested changes

2024-12-26 08:35 UTC, akihikodaki commented on client.ps1
> +    Restart-Service w32time
Restarting the time service is unnecessary either as we are not synchronizing time.

2024-12-30 12:02 UTC, akihikodaki requested changes

2024-12-30 12:02 UTC, akihikodaki commented on studio.ps1
> +    Restart-Service w32time
`Restart-Service` can be removed for the studio too.

2025-01-11 04:01 UTC, akihikodaki approved these changes

2025-01-13 10:03 UTC, kostyanf14 approved these changes

2025-01-13 10:03 UTC, merged